variables:
  PUBLISHED_PORT: "7081"
  CI_REGISTRY: " 146.169.46.199:5000"

stages:
  - build
  - test
  - package
  - deploy

image: docker:latest
image: maven:3.3.9-jdk-8

build:
  stage: build
  script:
    - mvn compile
  artifacts:
    untracked: true

test:
  stage: test
  script:
    - mvn test

package:
  stage: package
  script:
    - mvn package

deploy:
  stage: deploy
  variables:
    IMAGE_NAME: $CI_REGISTRY/$CI_PROJECT_PATH
    SERVICE_NAME: $CI_PROJECT_NAME-$PUBLISHED_PORT
  script:
    - docker build --build-arg published_port=$PUBLISHED_PORT -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
    - docker service rm $SERVICE_NAME || true
    - docker service create --name $SERVICE_NAME -p $PUBLISHED_PORT:$PUBLISHED_PORT -p :9091 --mount type=bind,src=/proc/kagent,dst=/var/log/host/kagent --network=tracer_default $IMAGE_NAME
  only:
    - master
  environment: staging
