stages:
  - build
  - test
  - package
  - deploy

image: docker:latest
image: maven:3.3.9-jdk-8

before_script:
  - mvn clean install

build:
  stage: build
  script:
    - mvn compile
  artifacts:
    untracked: true

test:
  stage: test
  script:
    - mvn test

package:
  stage: package
  script:
    - mvn package

deploy:
  stage: deploy
  script:
    - docker build -f Dockerfile -t cerebro .
    - docker run -p 8080:8080 -t cerebro
    - docker-machine ls
