variables:
  IMAGE_NAME: whispering-retreat-38205
  HEROKU_KEY: 19005357-bd65-4ee0-99fb-359f62d8b4ba

stages:
  - build
  - test
  - package
  - deploy

image: maven:3.3.9-jdk-8
image: docker:latest

build:
  stage: build
  script:
    - mvn compile
  artifacts:
    untracked: true

test:
  stage: test
  script:
    - mvn test

package:
  stage: package
  script:
    - mvn package

deploy:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$IMAGE_NAME --api-key=$HEROKU_KEY
  only:
    - master
  environment: staging

